name: Update badges

on:
  schedule:
    # runs nightly 
    - cron: "0 0 * * *"


jobs:
  update-readme:
    name: Update readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          #GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: rebelopsio/rebelopsio
          COMMIT_MESSAGE: "My commit message for badge update"
          CREDLY_USER: stephen-morgan.b43f1bc5
          CREDLY_SORT: RECENT
